# Generated by Django 2.2.13 on 2021-03-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_key'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
