# Generated by Django 2.2.2 on 2019-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190729_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ppaid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unlocked',
        ),
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
