# Generated by Django 2.2.2 on 2019-09-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190929_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.OneToOneField(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Key'),
        ),
    ]
