# Generated by Django 2.2.2 on 2019-09-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190929_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='key',
        ),
    ]
