# Generated by Django 2.2.13 on 2021-03-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210327_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
