# Generated by Django 2.2.13 on 2021-03-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210328_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_path',
            field=models.CharField(blank=True, default='placeholder.png', max_length=200),
        ),
    ]
