# Generated by Django 2.2.18 on 2021-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210328_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='install', max_length=200),
            preserve_default=False,
        ),
    ]
