# Generated by Django 2.2.18 on 2021-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
