# Generated by Django 2.2.2 on 2019-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
