# Generated by Django 2.2.2 on 2019-09-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='email',
            new_name='username',
        ),
    ]
