# Generated by Django 2.2.2 on 2019-09-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_key_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='key',
            name='username',
        ),
    ]
